### PR TITLE
Add Carthage support

### PR DESCRIPTION
**Pull request by soffes**

### CODE REVIEW

**Comment by nicklockwood** [comment]
Looks good - thanks!

**Comment by soffes** [comment]
Can you tag, release, and add a prebuilt library to the release on GitHub? Here's how to create a Carthage archive:

    $ carthage build --no-skip-current && carthage archive CountryPicker

:heart:

**Comment by nicklockwood** [comment]
@soffes Sorry for the wait. I'm not keen on including a binary framework in the repo, but I've added a new tag for you.

**Comment by soffes** [comment]
Thanks for merging! You don't add it to the repo, you simply upload it to GitHub's releases page. You can see I do this [here](https://github.com/soffes/crypto/releases).

**Pull request merged**
